name: qsprmodeler
channels:
  - conda-forge
dependencies:
  - h5py
  - importlib_resources
  - pip
  - python=3.11
  - jupyter
  - pandas=1.2.1
  - scikit-learn
  - matplotlib
  - openpyxl
  - pytest
  - pip:
    - tensorflow
    - rdkit
    - mordred
    - xgboost
    - dill
    - hyperopt
