#!/bin/bash
python activity_prediction_model_creation.py --training_conf mean_100/rf_classification_Morgan_1024.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_classification_Morgan_1024_pca_1024_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_classification_Morgan_1024_pca_128_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_classification_Morgan_1024_pca_256_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_classification_Morgan_1024_pca_512_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_classification_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_regression_Morgan_1024.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_regression_Morgan_1024_pca_1024_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_regression_Morgan_1024_pca_128_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_regression_Morgan_1024_pca_256_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_regression_Morgan_1024_pca_512_QED.json
python activity_prediction_model_creation.py --training_conf mean_100/rf_regression_QED.json
