#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/bagging_classification_Morgan_1024_pca_512_QED_HIV.json > HIV_bagging_1024_512_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/bagging_classification_Morgan_1024_HIV.json > HIV_bagging_1024.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/bagging_classification_Morgan_1024_pca_128_QED_HIV.json > HIV_bagging_1024_128_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/bagging_classification_Morgan_1024_pca_256_QED_HIV.json > HIV_bagging_1024_256_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/bagging_classification_Morgan_1024_pca_1024_QED_HIV.json > HIV_bagging_1024_1024_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/bagging_classification_QED_HIV.json > HIV_bagging_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/mlp_classification_QED_HIV.json > HIV_MLP_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/mlp_classification_Morgan_1024_pca_128_QED_HIV.json > HIV_MLP_1024_128_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/mlp_classification_Morgan_1024_pca_256_QED_HIV.json > HIV_MLP_1024_256_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/mlp_classification_Morgan_1024_pca_512_QED_HIV.json > HIV_MLP_1024_512_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/mlp_classification_Morgan_1024_pca_1024_QED_HIV.json > HIV_MLP_1024_1024_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/rf_classification_Morgan_1024_HIV.json > HIV_RF_1024.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/rf_classification_Morgan_1024_pca_128_QED_HIV.json > HIV_RF_1024_128_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/rf_classification_Morgan_1024_pca_256_QED_HIV.json > HIV_RF_1024_256_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/rf_classification_Morgan_1024_pca_512_QED_HIV.json > HIV_RF_1024_512_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/rf_classification_Morgan_1024_pca_1024_QED_HIV.json > HIV_RF_1024_1024_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/rf_classification_QED_HIV.json > HIV_RF_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/ridge_classification_Morgan_1024_HIV.json > HIV_ridge_1024.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/ridge_classification_Morgan_1024_pca_128_QED_HIV.json > HIV_ridge_1024_128_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/ridge_classification_Morgan_1024_pca_256_QED_HIV.json > HIV_ridge_1024_256_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/ridge_classification_Morgan_1024_pca_512_QED_HIV.json > HIV_ridge_1024_512_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/ridge_classification_Morgan_1024_pca_1024_QED_HIV.json > HIV_ridge_1024_1024_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/ridge_classification_QED_HIV.json > HIV_ridge_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/svm_classification_Morgan_1024_HIV.json > HIV_svm_1024.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/svm_classification_Morgan_1024_pca_128_QED_HIV.json > HIV_svm_1024_128_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/svm_classification_Morgan_1024_pca_256_QED_HIV.json > HIV_svm_1024_256_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/svm_classification_Morgan_1024_pca_512_QED_HIV.json > HIV_svm_1024_512_QED.txt
nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/svm_classification_Morgan_1024_pca_1024_QED_HIV.json > HIV_svm_1024_1024_QED.txt #to do
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/svm_classification_QED_HIV.json > HIV_svm_QED.txt
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/xgboost_classification_Morgan_1024_HIV.json > HIV_xgboost_1024.txt ##GPU not working
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/xgboost_classification_Morgan_1024_pca_128_QED_HIV.json > HIV_xgboost_1024_128_QED.txt ##
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/xgboost_classification_Morgan_1024_pca_256_QED_HIV.json > HIV_xgboost_1024_256_QED.txt ##
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/xgboost_classification_Morgan_1024_pca_512_QED_HIV.json > HIV_xgboost_1024_512_QED.txt ##
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/xgboost_classification_Morgan_1024_pca_1024_QED_HIV.json > HIV_xgboost_1024_1024_QED.txt ##
#nohup python activity_prediction_model_creation_DN.py --training_conf mean_no_limits/xgboost_classification_QED_HIV.json > HIV_xgboost_QED.txt #CPU